### ISSUE TITLE
Traceback (most recent call last):   File "/home/semaiov/Documents/dd2410_docker_ws/src/dd2410_docker/robotics_project/scripts/behaviour_trees/behaviors_list.py", line 208, in <module>     bt = rospy.get_param('/behaviour_tree') KeyError: '/behaviour_tree'

### ISSUE THREAD

**Issue by ZhangQuan-hub** [matiov/learn-BTs-with-GP#2]
Thanks for the gazebo simulation project you offered.

When I was running the project according to the README .md, I got an error. I strictly followed the steps shown in the file to ensure that the ubuntu and ros versions are correct, and that all dependencies are installed.

When I run this command:   " roslaunch robotics_project gazebo_project.launch"
I got this correctly:

![3eea05e173b3914247827e9dfad6193e](https://user-images.githubusercontent.com/95294457/229431335-127374b7-bec4-4b92-b0f6-420051784769.png)

But when I run the next command :   " roslaunch robotics_project launch_solution.launch  "to use the behaviour tree,I got the error:
Traceback (most recent call last):
  File "/home/semaiov/Documents/dd2410_docker_ws/src/dd2410_docker/robotics_project/scripts/behaviour_trees/behaviors_list.py", line 208, in <module>
    bt = rospy.get_param('/behaviour_tree')
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/client.py", line 467, in get_param
    return _param_server[param_name] #MasterProxy does all the magic for us
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/msproxy.py", line 123, in __getitem__
    raise KeyError(key)
KeyError: '/behaviour_tree'

I found the source of the error.It is from the python scripts: behaviors_list.py

![430b047df6eb83c69951d8ad814050e6](https://user-images.githubusercontent.com/95294457/229431364-566b58e7-d92f-47e0-a4ab-d09d75ea95fb.png)

It seemed that no rosparam or param named "/behaviour_tree"  was published.I checked all the .launch file  and all the .py file in robotics_project.,but found nowhere it was declared.

I tried using the commented out code in the script,using the string  "bt" ,but it still reported an error.

When you have spare time,please help me see how this should be corrected.By the way ,I got the same error whether inside the docker or  outside the docker.Thank you and best wishes!

**Comment by ZhangQuan-hub** [comment]
sovled!Thank you for your extraordinary paper and the splendid experiment.Learned a lot!
